/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a7d37fcd-7c22-410c-a522-d1b920b09dbb",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ZOMj88kGg",
    "aws_user_pools_web_client_id": "3vbdmfil0lfbrjhdcghlihl3pc",
    "oauth": {
        "domain": "thinkinsvelted8357177-d8357177-production.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
